import org.mule.util.StringUtils;

def extractAttendeeData(payload, boothId) {
    csv = StringUtils.strip(StringUtils.substringAfter(payload, 'QR-Code:'));
    data = StringUtils.splitAndTrim(csv, ',');
    flowVars.attendeeId = data[0];
    [
       'boothId':      boothId,
       'attendeeId' :  data[0],
       'fullName' :    data[1],
       'companyName' : data[2],
       'email' :       data[3]
    ];
}